name: Android CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Clean project
        run: ./gradlew clean

      # Debug builds
      - name: Build Debug APK
        run: ./gradlew assembleDebug

      - name: Build Debug AAB
        run: ./gradlew bundleDebug

      # Staging builds
      - name: Build Staging APK
        run: ./gradlew assembleStaging

      - name: Build Staging AAB
        run: ./gradlew bundleStaging

      # Upload Debug artifacts
      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: app/build/outputs/apk/debug/*.apk
          retention-days: 30

      - name: Upload Debug AAB
        uses: actions/upload-artifact@v4
        with:
          name: debug-aab
          path: app/build/outputs/bundle/debug/*.aab
          retention-days: 30

      # Upload Staging artifacts
      - name: Upload Staging APK
        uses: actions/upload-artifact@v4
        with:
          name: staging-apk
          path: app/build/outputs/apk/staging/*.apk
          retention-days: 30

      - name: Upload Staging AAB
        uses: actions/upload-artifact@v4
        with:
          name: staging-aab
          path: app/build/outputs/bundle/staging/*.aab
          retention-days: 30

      # Optional: Run tests
      - name: Run unit tests
        run: ./gradlew testDebugUnitTest testStagingUnitTest

      # Optional: Upload test reports
      - name: Upload test reports
        uses: actions/upload-artifact@v4
        if: always() # Subir reportes incluso si los tests fallan
        with:
          name: test-reports
          path: |
            app/build/reports/tests/
            app/build/test-results/
          retention-days: 7